name: scanner_angel
description: Una aplicación Flutter para escanear imágenes y convertirlas en PDF.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  pdf: ^3.6.0
  share: ^2.0.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
